name: pharmacheck
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  change_app_package_name: ^1.5.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/perfil.jpg
    - assets/images/salida.png
    - assets/images/mapa.jpg
    - assets/images/logo_pildora.png
    - assets/sounds/parte1.mp3
    - assets/sounds/parte2.mp3
    - assets/questions/questions.json

  fonts:
    - family: BarberChop
      fonts: 
        - asset: assets/fonts/BarberChop.ttf

    - family: Storyboo
      fonts:
        - asset: assets/fonts/Storyboo.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf


flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/logo_pildora.png"
